name: app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Fetch depedencies
        working-directory: ./z5cloud
        run: flutter pub get
      - name: Test
        working-directory: ./z5cloud
        run: flutter test

  buildWeb:
    runs-on: ubuntu-latest
    name: Build Web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Fetch depedencies
        working-directory: ./z5cloud
        run: flutter pub get
      - name: Generate build version
        id: info
        run: |
          echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
          echo "time=$(date +'%H%M%S')" >> $GITHUB_OUTPUT
          echo "short_commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build
        working-directory: ./z5cloud
        run: |
          version="${{ steps.info.outputs.date }}.${{ steps.info.outputs.time }}.${{ steps.info.outputs.short_commit_id }}"
          flutter build web --build-number=$version